# Generated by Django 3.1.7 on 2021-04-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj30',
            name='e_p',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dj30',
            name='p_div',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dj30',
            name='p_e',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sp500',
            name='e_p',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sp500',
            name='p_div',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sp500',
            name='p_e',
            field=models.FloatField(null=True),
        ),
    ]
