# Generated by Django 3.1.7 on 2021-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_rest', '0002_auto_20210417_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('p_div', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('momentum', models.FloatField(null=True)),
                ('ma10', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Divs',
        ),
        migrations.RemoveField(
            model_name='sp500',
            name='p_div',
        ),
    ]
