# Generated by Django 3.1.7 on 2021-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_rest', '0003_auto_20210418_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='avg_pe',
            field=models.FloatField(null=True),
        ),
    ]
